SIT-17803 install file locking msi
resilio-inc/connect-scripts pull request #58
Opened 2024-08-30 11:05 UTC by sebastian-nowak-resilio

readme.md not updated, I'm not sure if needed as the feature is still not released

2024-08-31 03:58 UTC, roman-zanin requested changes
1) Verify-UpgradePossible (line 231) function should check for driver MSI presence and return error code if its not there. 
It should show the warning only if upgrade goes to a version 4.1* (or whatever would be the version that supports file locks). 
Also, a new error code must appear in the readme.md that helps customer to identify they are missing driver MSI
2) The actual attempt to deploy a driver (line 575) should also happen only if customer goes to v4.1 since if there would be a customer who updates to (say) 4.0.5 - the script will fail due to MSI absence.
3) There must be a parameter that allows to disable both verification and installation of a driver, see example on line 5. This parameter must also be exposed in file upgrade-post-download.cmd.copy_to_trigger, see line 5..8 of a respective file as an example

2024-09-04 13:51 UTC, roman-zanin approved these changes

2024-09-09 18:49 UTC, HelenYakubovich commented
typo in readme - Resilio-File-Locking-Driver_x64.**msie** file is missing

2024-09-10 09:03 UTC, sebastian-nowak-resilio commented
> typo in readme and script - Resilio-File-Locking-Driver_x64.**msie** file is missing

thx - fixed

2024-09-16 13:18 UTC, merged